### ISSUE TITLE
Unable to access files on HDFS

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/FlareControl#14]
I have setup the hadoop environment and started the hdfs. I put in the log files which are to be archived and tagged in hdfs location: /user/root/flare_files. Verified the files are present. Steps:
hadoop fs -mkdir -p /user/root/flare_files
hdfs dfs -put /root/FlareFiles/TestData1.data /user/root/flare_files
hdfs dfs -ls /user/root/flare_files

In the pipeline config, I have added localhost to the hostslist for both input and output. But I am getting the following error:
Exception in thread "main" org.apache.hadoop.mapred.InvalidInputException: Input path does not exist: file:/root/FlareControl/localhost/user/root/flare_files/TestData1.data
       	at org.apache.hadoop.mapred.FileInputFormat.singleThreadedListStatus(FileInputFormat.java:285)
       	at org.apache.hadoop.mapred.FileInputFormat.listStatus(FileInputFormat.java:228)
       	at org.apache.hadoop.mapred.FileInputFormat.getSplits(FileInputFormat.java:313)
       	at org.apache.spark.rdd.HadoopRDD.getPartitions(HadoopRDD.scala:207)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
       	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
       	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
       	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
       	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
       	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
       	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
       	at scala.Option.getOrElse(Option.scala:120)
       	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
       	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1903)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply$mcV$sp(PairRDDFunctions.scala:1124)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopDataset$1.apply(PairRDDFunctions.scala:1065)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
       	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
       	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopDataset(PairRDDFunctions.scala:1065)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply$mcV$sp(PairRDDFunctions.scala:989)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$4.apply(PairRDDFunctions.scala:965)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
       	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
       	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:965)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply$mcV$sp(PairRDDFunctions.scala:897)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
       	at org.apache.spark.rdd.PairRDDFunctions$$anonfun$saveAsHadoopFile$1.apply(PairRDDFunctions.scala:897)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
       	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
       	at org.apache.spark.rdd.PairRDDFunctions.saveAsHadoopFile(PairRDDFunctions.scala:896)
       	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply$mcV$sp(RDD.scala:1426)
       	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
       	at org.apache.spark.rdd.RDD$$anonfun$saveAsTextFile$1.apply(RDD.scala:1405)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
       	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
       	at org.apache.spark.rdd.RDD.saveAsTextFile(RDD.scala:1405)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1.apply(demoTest.scala:194)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1.apply(demoTest.scala:114)
       	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
       	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1.executePipeline(demoTest.scala:114)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$.main(demoTest.scala:61)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1.main(demoTest.scala)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
       	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
       	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
       	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
       	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

It looks like we are not accessing the core-site.xml and hdfs-site.xml configuration in Scala.

**Comment by ligadata-dhaval** [comment]
Closing this issue as it is a duplicate.
