### ISSUE TITLE
Serialization of pipeline object fails

### ISSUE THREAD

**Issue by ligadata-dhaval** [LigaData/FlareControl#16]
I am facing the below error:

Exception in thread "main" org.apache.spark.SparkException: Task not serializable
       	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:304)
       	at org.apache.spark.util.ClosureCleaner$.org$apache$spark$util$ClosureCleaner$$clean(ClosureCleaner.scala:294)
       	at org.apache.spark.util.ClosureCleaner$.clean(ClosureCleaner.scala:122)
       	at org.apache.spark.SparkContext.clean(SparkContext.scala:2021)
       	at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:314)
       	at org.apache.spark.rdd.RDD$$anonfun$map$1.apply(RDD.scala:313)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
       	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
       	at org.apache.spark.rdd.RDD.withScope(RDD.scala:306)
       	at org.apache.spark.rdd.RDD.map(RDD.scala:313)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1.apply(demoTest.scala:124)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1.apply(demoTest.scala:115)
       	at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
       	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:108)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1.executePipeline(demoTest.scala:115)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$.main(demoTest.scala:62)
       	at com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1.main(demoTest.scala)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:672)
       	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
       	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
       	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)
       	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: java.io.NotSerializableException: java.io.PrintStream
Serialization stack:
       	- object not serializable (class: java.io.PrintStream, value: java.io.PrintStream@64c781a9)
       	- field (class: org.apache.logging.log4j.simple.SimpleLogger, name: stream, type: class java.io.PrintStream)
       	- object (class org.apache.logging.log4j.simple.SimpleLogger, org.apache.logging.log4j.simple.SimpleLogger@1d8b0500)
       	- field (class: com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1, name: logger, type: interface org.apache.logging.log4j.Logger)
       	- object (class com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1, com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1@62dbe64e)
       	- field (class: com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1, name: $outer, type: class com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1)
       	- object (class com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1, <function1>)
       	- field (class: com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1$$anonfun$3, name: $outer, type: class com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1)
       	- object (class com.ligadata.flarecontrol.pipelineprocessor.p1.GeneratedPipelineSpark_p1$$anonfun$executePipeline$1$$anonfun$3, <function1>)
       	at org.apache.spark.serializer.SerializationDebugger$.improveException(SerializationDebugger.scala:40)
       	at org.apache.spark.serializer.JavaSerializationStream.writeObject(JavaSerializer.scala:47)
       	at org.apache.spark.serializer.JavaSerializerInstance.serialize(JavaSerializer.scala:84)
       	at org.apache.spark.util.ClosureCleaner$.ensureSerializable(ClosureCleaner.scala:301)
       	... 25 more

**Comment by ligadata-dhaval** [comment]
Log4j is not serializable and so it is not serialized by adding @transient annotation. Checked in the code in PiplineChecking and closing the issue.
